// Generated by build-progress.mjs — do not edit by hand.
window.__LOOM__ = {
  "generatedAt": "2026-06-30T12:47:28.652Z",
  "catalogPresent": true,
  "totals": {
    "features": 124,
    "done": 12
  },
  "phases": [
    {
      "key": "H",
      "label": "Foundations & safety nets",
      "total": 14,
      "done": 11,
      "items": [
        {
          "name": "Set up the project skeleton",
          "blurb": "Creates the base project, dependencies, and build and test commands everything else is built on.",
          "hasTests": false,
          "testsDone": null,
          "builtDone": true,
          "status": "done"
        },
        {
          "name": "Code-quality safety checks",
          "blurb": "Automatic checks that block risky coding patterns before they reach the project.",
          "hasTests": false,
          "testsDone": null,
          "builtDone": true,
          "status": "done"
        },
        {
          "name": "Wire up swappable host services",
          "blurb": "Sets up replaceable connections to host services so nothing reaches global state directly.",
          "hasTests": false,
          "testsDone": null,
          "builtDone": true,
          "status": "done"
        },
        {
          "name": "Extension start-up and test harness",
          "blurb": "Starts the add-on inside the host and provides a test rig for end-to-end runs.",
          "hasTests": false,
          "testsDone": null,
          "builtDone": true,
          "status": "done"
        },
        {
          "name": "Scriptable fake model for tests",
          "blurb": "Lets tests script what the stand-in model replies, so behaviour can be checked reliably.",
          "hasTests": false,
          "testsDone": null,
          "builtDone": true,
          "status": "done"
        },
        {
          "name": "Scriptable nested calls and sub-assistants",
          "blurb": "Extends the test stand-in to script completed nested calls and separate sub-assistant runs.",
          "hasTests": false,
          "testsDone": null,
          "builtDone": true,
          "status": "done"
        },
        {
          "name": "Coverage gate for requirements",
          "blurb": "Automatically checks every requirement and message code has a matching test.",
          "hasTests": false,
          "testsDone": null,
          "builtDone": true,
          "status": "done"
        },
        {
          "name": "Pre-release coverage warning pass",
          "blurb": "Warns about coverage gaps before the strict release check turns them into failures.",
          "hasTests": false,
          "testsDone": null,
          "builtDone": false,
          "status": "waiting"
        },
        {
          "name": "Audit error-catching exemptions",
          "blurb": "Checks that every broad error-catch exemption points to a real, valid reason.",
          "hasTests": false,
          "testsDone": null,
          "builtDone": true,
          "status": "done"
        },
        {
          "name": "Check every requirement has an owner",
          "blurb": "Confirms each requirement is assigned to at least one piece of planned work.",
          "hasTests": false,
          "testsDone": null,
          "builtDone": true,
          "status": "done"
        },
        {
          "name": "Find unlabelled must-do rules",
          "blurb": "Scans the spec for mandatory rules that lack a tracked owner or test.",
          "hasTests": false,
          "testsDone": null,
          "builtDone": true,
          "status": "done"
        },
        {
          "name": "Check shared requirements are fully tested",
          "blurb": "Ensures each part of a requirement split across tasks has its own test.",
          "hasTests": false,
          "testsDone": null,
          "builtDone": true,
          "status": "done"
        },
        {
          "name": "Turn on the release coverage gate",
          "blurb": "Flips coverage checks to the real project at release time, after smoke and review.",
          "hasTests": false,
          "testsDone": null,
          "builtDone": false,
          "status": "waiting"
        },
        {
          "name": "End-to-end integration check",
          "blurb": "Runs one rich example through the whole pipeline to catch cross-feature regressions.",
          "hasTests": false,
          "testsDone": null,
          "builtDone": false,
          "status": "waiting"
        }
      ]
    },
    {
      "key": "M",
      "label": "First end-to-end command",
      "total": 1,
      "done": 1,
      "items": [
        {
          "name": "Run a basic loom command",
          "blurb": "The smallest working command: read a file, ask the model once, and stream the reply.",
          "hasTests": true,
          "testsDone": true,
          "builtDone": true,
          "status": "done"
        }
      ]
    },
    {
      "key": "V1",
      "label": "Reading loom source",
      "total": 2,
      "done": 0,
      "items": [
        {
          "name": "Read and tokenise loom source",
          "blurb": "Turns raw loom text into the tokens the rest of the language works with.",
          "hasTests": true,
          "testsDone": false,
          "builtDone": false,
          "status": "waiting"
        },
        {
          "name": "Read text, number, and path values",
          "blurb": "Reads quoted strings, numbers, and file paths written directly in loom source.",
          "hasTests": true,
          "testsDone": false,
          "builtDone": false,
          "status": "waiting"
        }
      ]
    },
    {
      "key": "V2",
      "label": "Types and values",
      "total": 5,
      "done": 0,
      "items": [
        {
          "name": "Read type and value notation",
          "blurb": "Parses the notation for declaring types and writing literal values in loom.",
          "hasTests": true,
          "testsDone": false,
          "builtDone": false,
          "status": "waiting"
        },
        {
          "name": "Check type compatibility",
          "blurb": "Decides whether one type fits where another is expected, with clear mismatch messages.",
          "hasTests": true,
          "testsDone": false,
          "builtDone": false,
          "status": "waiting"
        },
        {
          "name": "Represent values at runtime",
          "blurb": "Defines how loom values are held in memory and compared for equality.",
          "hasTests": true,
          "testsDone": false,
          "builtDone": false,
          "status": "waiting"
        },
        {
          "name": "Format numbers consistently",
          "blurb": "Renders whole numbers and decimals in one consistent text form across the system.",
          "hasTests": true,
          "testsDone": false,
          "builtDone": false,
          "status": "waiting"
        },
        {
          "name": "Translate field names on the wire",
          "blurb": "Converts field names between loom-side and external JSON forms in both directions.",
          "hasTests": true,
          "testsDone": false,
          "builtDone": false,
          "status": "waiting"
        }
      ]
    },
    {
      "key": "V3",
      "label": "Expressions and control flow",
      "total": 7,
      "done": 0,
      "items": [
        {
          "name": "Evaluate expressions",
          "blurb": "Computes expressions: maths, comparisons, logic, and building objects and arrays.",
          "hasTests": true,
          "testsDone": false,
          "builtDone": false,
          "status": "waiting"
        },
        {
          "name": "Declare and reassign variables",
          "blurb": "Adds fixed and changeable variables with rules on what may be reassigned.",
          "hasTests": true,
          "testsDone": false,
          "builtDone": false,
          "status": "waiting"
        },
        {
          "name": "Branch and loop",
          "blurb": "Adds if, for, while, break, and continue for branching and repetition.",
          "hasTests": true,
          "testsDone": false,
          "builtDone": false,
          "status": "waiting"
        },
        {
          "name": "Define and return from functions",
          "blurb": "Adds top-level functions with inferred return types and return rules.",
          "hasTests": true,
          "testsDone": false,
          "builtDone": false,
          "status": "waiting"
        },
        {
          "name": "Built-in text helpers",
          "blurb": "Adds common text operations like split, trim, change case, and contains.",
          "hasTests": true,
          "testsDone": false,
          "builtDone": false,
          "status": "waiting"
        },
        {
          "name": "Built-in list helpers",
          "blurb": "Adds common list operations like join, slice, includes, and length.",
          "hasTests": true,
          "testsDone": false,
          "builtDone": false,
          "status": "waiting"
        },
        {
          "name": "Built-in object helpers",
          "blurb": "Adds object helpers to read keys, read values, and check for a field.",
          "hasTests": true,
          "testsDone": false,
          "builtDone": false,
          "status": "waiting"
        }
      ]
    },
    {
      "key": "V4",
      "label": "Errors and results",
      "total": 7,
      "done": 0,
      "items": [
        {
          "name": "Pattern matching and results",
          "blurb": "Adds match, the success-or-error result type, and the shortcut error operator.",
          "hasTests": true,
          "testsDone": false,
          "builtDone": false,
          "status": "waiting"
        },
        {
          "name": "Handle unrecoverable runtime errors",
          "blurb": "Defines the fixed set of fatal runtime errors and their standard messages.",
          "hasTests": true,
          "testsDone": false,
          "builtDone": false,
          "status": "waiting"
        },
        {
          "name": "Define success, failure, cancelled",
          "blurb": "Classifies every run as success, failure, or cancelled, keeping work done so far.",
          "hasTests": true,
          "testsDone": false,
          "builtDone": false,
          "status": "waiting"
        },
        {
          "name": "Define question-failure shapes",
          "blurb": "Defines the set of error shapes a model question can fail with.",
          "hasTests": true,
          "testsDone": false,
          "builtDone": false,
          "status": "waiting"
        },
        {
          "name": "Report load-time problems",
          "blurb": "Surfaces problems found before running as notes, not as run outcomes.",
          "hasTests": true,
          "testsDone": false,
          "builtDone": false,
          "status": "waiting"
        },
        {
          "name": "Keep completed work on failure",
          "blurb": "Guarantees finished side effects survive a later failure; nothing is undone.",
          "hasTests": true,
          "testsDone": false,
          "builtDone": false,
          "status": "waiting"
        },
        {
          "name": "Report reload-time problems",
          "blurb": "Surfaces problems found while reloading changed files as notes, not run outcomes.",
          "hasTests": true,
          "testsDone": false,
          "builtDone": false,
          "status": "waiting"
        }
      ]
    },
    {
      "key": "V5",
      "label": "Schemas and validation",
      "total": 6,
      "done": 0,
      "items": [
        {
          "name": "Declare data schemas",
          "blurb": "Adds declarations for object, alias, and enum data shapes with named fields.",
          "hasTests": true,
          "testsDone": false,
          "builtDone": false,
          "status": "waiting"
        },
        {
          "name": "Either-or and recursive schemas",
          "blurb": "Supports either-or data shapes, self-referencing schemas, and cycle detection.",
          "hasTests": true,
          "testsDone": false,
          "builtDone": false,
          "status": "waiting"
        },
        {
          "name": "Attach descriptions to schemas",
          "blurb": "Lets doc comments become field descriptions carried into the schema.",
          "hasTests": true,
          "testsDone": false,
          "builtDone": false,
          "status": "waiting"
        },
        {
          "name": "Reject unsupported schema features",
          "blurb": "Accepts only the supported schema subset and clearly rejects everything else.",
          "hasTests": true,
          "testsDone": false,
          "builtDone": false,
          "status": "waiting"
        },
        {
          "name": "Limit data nesting depth",
          "blurb": "Rejects data nested deeper than the safety limit before validation runs.",
          "hasTests": true,
          "testsDone": false,
          "builtDone": false,
          "status": "waiting"
        },
        {
          "name": "Finalise and fingerprint schemas",
          "blurb": "Converts schemas to final form and computes a stable identifying fingerprint.",
          "hasTests": true,
          "testsDone": false,
          "builtDone": false,
          "status": "waiting"
        }
      ]
    },
    {
      "key": "V6",
      "label": "Prompt-file settings",
      "total": 5,
      "done": 0,
      "items": [
        {
          "name": "Read prompt-file settings",
          "blurb": "Parses the settings block at the top of a loom file, with defaults and warnings.",
          "hasTests": true,
          "testsDone": false,
          "builtDone": false,
          "status": "waiting"
        },
        {
          "name": "Declare command parameters",
          "blurb": "Defines a command's parameters, their types, and default values.",
          "hasTests": true,
          "testsDone": false,
          "builtDone": false,
          "status": "waiting"
        },
        {
          "name": "Declare which tools a command uses",
          "blurb": "Defines the set of tools a command may call, with renaming and clash checks.",
          "hasTests": true,
          "testsDone": false,
          "builtDone": false,
          "status": "waiting"
        },
        {
          "name": "Fill in the system-prompt template",
          "blurb": "Builds a sub-assistant's system prompt, substituting allowed values into the template.",
          "hasTests": true,
          "testsDone": false,
          "builtDone": false,
          "status": "waiting"
        },
        {
          "name": "Set retry and tool-round limits",
          "blurb": "Adds settings for answer-retry attempts and the maximum number of tool-use rounds.",
          "hasTests": true,
          "testsDone": false,
          "builtDone": false,
          "status": "waiting"
        }
      ]
    },
    {
      "key": "V7",
      "label": "Error & warning messages",
      "total": 4,
      "done": 0,
      "items": [
        {
          "name": "Build error and warning messages",
          "blurb": "Defines how error and warning messages are shaped, formatted, and collected together.",
          "hasTests": true,
          "testsDone": true,
          "builtDone": false,
          "status": "ready"
        },
        {
          "name": "Register message codes",
          "blurb": "Maintains the checked list of all error and warning codes loom can emit.",
          "hasTests": true,
          "testsDone": false,
          "builtDone": false,
          "status": "waiting"
        },
        {
          "name": "Fill in message details",
          "blurb": "Renders the variable parts of messages, like values, types, and source text.",
          "hasTests": true,
          "testsDone": false,
          "builtDone": false,
          "status": "waiting"
        },
        {
          "name": "Deliver messages to the host",
          "blurb": "Sends batched error and warning messages to the host, with fallback paths.",
          "hasTests": true,
          "testsDone": false,
          "builtDone": false,
          "status": "waiting"
        }
      ]
    },
    {
      "key": "V8",
      "label": "Talking to the host app",
      "total": 5,
      "done": 0,
      "items": [
        {
          "name": "Cancellation check-in service",
          "blurb": "Provides the swappable service that pauses to check for cancellation at set points.",
          "hasTests": true,
          "testsDone": false,
          "builtDone": false,
          "status": "waiting"
        },
        {
          "name": "File access service",
          "blurb": "Provides the swappable service for reading files, including raw bytes and paths.",
          "hasTests": true,
          "testsDone": false,
          "builtDone": false,
          "status": "waiting"
        },
        {
          "name": "Data validation service",
          "blurb": "Provides the swappable service that validates data against a schema in one pass.",
          "hasTests": true,
          "testsDone": false,
          "builtDone": false,
          "status": "waiting"
        },
        {
          "name": "Time and id services",
          "blurb": "Provides swappable services for the current time, timers, and unique ids.",
          "hasTests": true,
          "testsDone": false,
          "builtDone": false,
          "status": "waiting"
        },
        {
          "name": "File-watch and token-count services",
          "blurb": "Provides swappable services for watching files and estimating token counts.",
          "hasTests": true,
          "testsDone": false,
          "builtDone": false,
          "status": "waiting"
        }
      ]
    },
    {
      "key": "V9",
      "label": "Running inside the host app",
      "total": 17,
      "done": 0,
      "items": [
        {
          "name": "Check the host is compatible",
          "blurb": "Checks required host features exist at start-up and refuses to run if any are missing.",
          "hasTests": true,
          "testsDone": false,
          "builtDone": false,
          "status": "waiting"
        },
        {
          "name": "Register the command and watch files",
          "blurb": "Registers loom commands with the host and rebuilds them when files change.",
          "hasTests": true,
          "testsDone": false,
          "builtDone": false,
          "status": "waiting"
        },
        {
          "name": "Drive a chat-mode turn",
          "blurb": "Runs a chat-mode question, gets the reply, and limits which tools are active.",
          "hasTests": true,
          "testsDone": false,
          "builtDone": false,
          "status": "waiting"
        },
        {
          "name": "Report runtime events to the host",
          "blurb": "Sends runtime status events to the host with consistent display and logging.",
          "hasTests": true,
          "testsDone": false,
          "builtDone": false,
          "status": "waiting"
        },
        {
          "name": "Track running commands",
          "blurb": "Keeps a registry of in-flight command runs so they can be managed and cleaned up.",
          "hasTests": true,
          "testsDone": false,
          "builtDone": false,
          "status": "waiting"
        },
        {
          "name": "Register tools per command",
          "blurb": "Wires up each command's tools, with friendly labels and clash handling.",
          "hasTests": true,
          "testsDone": false,
          "builtDone": false,
          "status": "waiting"
        },
        {
          "name": "Clean up when a session ends",
          "blurb": "Tears down running work in the right order when the host session shuts down.",
          "hasTests": true,
          "testsDone": false,
          "builtDone": false,
          "status": "waiting"
        },
        {
          "name": "Handle unknown shutdown reasons",
          "blurb": "Validates the session-end reason and routes unrecognised ones safely.",
          "hasTests": true,
          "testsDone": false,
          "builtDone": false,
          "status": "waiting"
        },
        {
          "name": "Run isolated sub-assistants",
          "blurb": "Runs a sub-assistant in its own private session and always disposes it afterward.",
          "hasTests": true,
          "testsDone": false,
          "builtDone": false,
          "status": "waiting"
        },
        {
          "name": "Call the model and map provider errors",
          "blurb": "Makes the model call and translates provider errors into typed failures.",
          "hasTests": true,
          "testsDone": false,
          "builtDone": false,
          "status": "waiting"
        },
        {
          "name": "Abort start-up on critical failures",
          "blurb": "Stops the whole add-on when a critical start-up registration call fails.",
          "hasTests": true,
          "testsDone": false,
          "builtDone": false,
          "status": "waiting"
        },
        {
          "name": "Mark a session needing reload",
          "blurb": "Marks a swapped-in session as degraded and blocks it until reloaded.",
          "hasTests": true,
          "testsDone": false,
          "builtDone": false,
          "status": "blocked"
        },
        {
          "name": "Track command-registry state",
          "blurb": "Tracks whether the command registry is live, shutting down, or needs a reload.",
          "hasTests": true,
          "testsDone": false,
          "builtDone": false,
          "status": "waiting"
        },
        {
          "name": "Map chat transport errors",
          "blurb": "Turns chat-mode transport failures into typed errors, with cancellation taking priority.",
          "hasTests": true,
          "testsDone": false,
          "builtDone": false,
          "status": "waiting"
        },
        {
          "name": "Safely abandon cancelled sub-assistants",
          "blurb": "Ensures a cancelled sub-assistant can't leak a late result into later work.",
          "hasTests": true,
          "testsDone": false,
          "builtDone": false,
          "status": "waiting"
        },
        {
          "name": "Survive non-critical start-up failures",
          "blurb": "Keeps running when a non-critical registration call fails, dropping only that piece.",
          "hasTests": true,
          "testsDone": false,
          "builtDone": false,
          "status": "waiting"
        },
        {
          "name": "Recover when file-watching stops",
          "blurb": "Leaves a stopped file watcher down and prompts the user to reload.",
          "hasTests": true,
          "testsDone": false,
          "builtDone": false,
          "status": "waiting"
        }
      ]
    },
    {
      "key": "V10",
      "label": "Finding loom files and settings",
      "total": 4,
      "done": 0,
      "items": [
        {
          "name": "Find loom files across locations",
          "blurb": "Searches the known places for loom files and resolves naming clashes between them.",
          "hasTests": true,
          "testsDone": false,
          "builtDone": false,
          "status": "waiting"
        },
        {
          "name": "Find loom files in packages",
          "blurb": "Locates loom files listed by packages, with glob matching and bounded scanning.",
          "hasTests": true,
          "testsDone": false,
          "builtDone": false,
          "status": "waiting"
        },
        {
          "name": "Read and combine settings",
          "blurb": "Reads settings from each source and merges them with project overriding global.",
          "hasTests": true,
          "testsDone": false,
          "builtDone": false,
          "status": "waiting"
        },
        {
          "name": "Smooth reloads on file changes",
          "blurb": "Waits out rapid file changes before reloading and serialises rebuilds safely.",
          "hasTests": true,
          "testsDone": false,
          "builtDone": false,
          "status": "waiting"
        }
      ]
    },
    {
      "key": "V11",
      "label": "Filling command arguments from chat",
      "total": 10,
      "done": 0,
      "items": [
        {
          "name": "Pick the model for filling arguments",
          "blurb": "Resolves which model fills command arguments and checks it supports the needed features.",
          "hasTests": true,
          "testsDone": false,
          "builtDone": false,
          "status": "waiting"
        },
        {
          "name": "Feed chat history to argument filling",
          "blurb": "Optionally includes recent conversation so argument-filling has context, rendered compactly.",
          "hasTests": true,
          "testsDone": false,
          "builtDone": false,
          "status": "waiting"
        },
        {
          "name": "Shape the argument-filling request",
          "blurb": "Defines the data shape the model must return when filling in command arguments.",
          "hasTests": true,
          "testsDone": false,
          "builtDone": false,
          "status": "waiting"
        },
        {
          "name": "Build the argument-filling instructions",
          "blurb": "Builds the instructions that tell the model how to fill in command arguments.",
          "hasTests": true,
          "testsDone": false,
          "builtDone": false,
          "status": "waiting"
        },
        {
          "name": "Consistent argument-filling notes",
          "blurb": "Renders short status notes and makes argument-filling repeatable run to run.",
          "hasTests": true,
          "testsDone": false,
          "builtDone": false,
          "status": "waiting"
        },
        {
          "name": "Retry argument-filling on failure",
          "blurb": "Retries argument-filling a limited number of times and explains why it failed.",
          "hasTests": true,
          "testsDone": false,
          "builtDone": false,
          "status": "waiting"
        },
        {
          "name": "Fill missing arguments with defaults",
          "blurb": "Fills absent arguments with their defaults, then re-checks the whole set is valid.",
          "hasTests": true,
          "testsDone": false,
          "builtDone": false,
          "status": "waiting"
        },
        {
          "name": "Show which arguments used defaults",
          "blurb": "Displays the filled-in arguments, marking any that fell back to a default value.",
          "hasTests": true,
          "testsDone": false,
          "builtDone": false,
          "status": "waiting"
        },
        {
          "name": "Trim chat history to fit",
          "blurb": "Selects recent whole turns within size limits before handing them to argument-filling.",
          "hasTests": true,
          "testsDone": false,
          "builtDone": false,
          "status": "waiting"
        },
        {
          "name": "Cancel argument-filling mid-run",
          "blurb": "Stops the argument-filling model call promptly when the user cancels.",
          "hasTests": true,
          "testsDone": false,
          "builtDone": false,
          "status": "waiting"
        }
      ]
    },
    {
      "key": "V12",
      "label": "Running a slash command",
      "total": 2,
      "done": 0,
      "items": [
        {
          "name": "Dispatch and stream a command",
          "blurb": "Runs a slash command, streams the reply, and handles extra typed-in text.",
          "hasTests": true,
          "testsDone": false,
          "builtDone": false,
          "status": "waiting"
        },
        {
          "name": "Explain command failures clearly",
          "blurb": "Formats a failed command's error into a readable note tracing where it came from.",
          "hasTests": true,
          "testsDone": false,
          "builtDone": false,
          "status": "waiting"
        }
      ]
    },
    {
      "key": "V13",
      "label": "Asking the model questions",
      "total": 7,
      "done": 0,
      "items": [
        {
          "name": "Build a question for the model",
          "blurb": "Turns an in-loom question template into the actual text sent to the model.",
          "hasTests": true,
          "testsDone": false,
          "builtDone": false,
          "status": "waiting"
        },
        {
          "name": "Infer the answer's expected shape",
          "blurb": "Works out what data shape a typed question expects back from the model.",
          "hasTests": true,
          "testsDone": false,
          "builtDone": false,
          "status": "waiting"
        },
        {
          "name": "Let the model use tools while answering",
          "blurb": "Runs the model's tool-use loop and gets a final typed answer back.",
          "hasTests": true,
          "testsDone": false,
          "builtDone": false,
          "status": "waiting"
        },
        {
          "name": "Retry malformed model answers",
          "blurb": "Re-asks the model when its answer doesn't fit, up to a set number of times.",
          "hasTests": true,
          "testsDone": false,
          "builtDone": false,
          "status": "waiting"
        },
        {
          "name": "Safely abandon cancelled questions",
          "blurb": "Ensures a cancelled model question can't leak a late result into later work.",
          "hasTests": true,
          "testsDone": false,
          "builtDone": false,
          "status": "waiting"
        },
        {
          "name": "Log discarded question results",
          "blurb": "Flags when a question's answer is thrown away, keeping any error visible in logs.",
          "hasTests": true,
          "testsDone": false,
          "builtDone": false,
          "status": "waiting"
        },
        {
          "name": "Write retry follow-up messages",
          "blurb": "Builds the exact follow-up text sent to the model when re-asking a question.",
          "hasTests": true,
          "testsDone": false,
          "builtDone": false,
          "status": "waiting"
        }
      ]
    },
    {
      "key": "V14",
      "label": "Calling tools",
      "total": 7,
      "done": 0,
      "items": [
        {
          "name": "Call a tool from loom code",
          "blurb": "Lets loom code call a tool directly, with argument checks and clear error types.",
          "hasTests": true,
          "testsDone": false,
          "builtDone": false,
          "status": "waiting"
        },
        {
          "name": "Run parallel tool calls together",
          "blurb": "Waits for a batch of simultaneous tool calls to finish before continuing.",
          "hasTests": true,
          "testsDone": false,
          "builtDone": false,
          "status": "waiting"
        },
        {
          "name": "Route unusual tool-call outcomes",
          "blurb": "Sends odd tool-call failures to the right channel instead of one generic error.",
          "hasTests": true,
          "testsDone": false,
          "builtDone": false,
          "status": "waiting"
        },
        {
          "name": "Handle host-blocked tool calls",
          "blurb": "Surfaces a tool the host refused or errored as a real failure, never a silent success.",
          "hasTests": true,
          "testsDone": false,
          "builtDone": false,
          "status": "waiting"
        },
        {
          "name": "Reject too-deeply-nested tool data",
          "blurb": "Blocks tool-call arguments nested past the safety limit before validation.",
          "hasTests": true,
          "testsDone": false,
          "builtDone": false,
          "status": "waiting"
        },
        {
          "name": "Safely abandon cancelled tool calls",
          "blurb": "Ensures a cancelled tool call can't leak a late result into later work.",
          "hasTests": true,
          "testsDone": false,
          "builtDone": false,
          "status": "waiting"
        },
        {
          "name": "Turn tool results into typed values",
          "blurb": "Converts a tool's raw result into a typed success-or-error value loom code can use.",
          "hasTests": true,
          "testsDone": false,
          "builtDone": false,
          "status": "waiting"
        }
      ]
    },
    {
      "key": "V15",
      "label": "Calling other loom files",
      "total": 13,
      "done": 0,
      "items": [
        {
          "name": "Call one loom file from another",
          "blurb": "Resolves and loads a called loom file safely, caching parsed results during a run.",
          "hasTests": true,
          "testsDone": false,
          "builtDone": false,
          "status": "waiting"
        },
        {
          "name": "Limit and detect call loops",
          "blurb": "Caps how deep loom-to-loom calls can nest and detects circular call chains.",
          "hasTests": true,
          "testsDone": false,
          "builtDone": false,
          "status": "waiting"
        },
        {
          "name": "Import shared loom library files",
          "blurb": "Loads reusable library files and reports import and naming problems.",
          "hasTests": true,
          "testsDone": false,
          "builtDone": false,
          "status": "waiting"
        },
        {
          "name": "Pause parent during nested chat call",
          "blurb": "Suspends the parent's active tools while a nested chat call runs, then restores them.",
          "hasTests": true,
          "testsDone": false,
          "builtDone": false,
          "status": "waiting"
        },
        {
          "name": "Refresh caches on file edits",
          "blurb": "Drops stale cached parses for changed files and everything that imports them.",
          "hasTests": true,
          "testsDone": false,
          "builtDone": false,
          "status": "waiting"
        },
        {
          "name": "Report bad cross-file calls",
          "blurb": "Flags wrong arguments, return types, or missing files when calling another loom file.",
          "hasTests": true,
          "testsDone": false,
          "builtDone": false,
          "status": "waiting"
        },
        {
          "name": "Track where calls came from",
          "blurb": "Records each call's source file and line so failures can be traced back.",
          "hasTests": true,
          "testsDone": false,
          "builtDone": false,
          "status": "waiting"
        },
        {
          "name": "Safely abandon cancelled nested calls",
          "blurb": "Ensures a cancelled nested loom call can't leak a late result into later work.",
          "hasTests": true,
          "testsDone": false,
          "builtDone": false,
          "status": "waiting"
        },
        {
          "name": "Control what library files share",
          "blurb": "Defines which library items importers can see and which re-export onward.",
          "hasTests": true,
          "testsDone": false,
          "builtDone": false,
          "status": "waiting"
        },
        {
          "name": "Reject too-deeply-nested call data",
          "blurb": "Blocks call arguments or return values nested past the safety limit.",
          "hasTests": true,
          "testsDone": false,
          "builtDone": false,
          "status": "waiting"
        },
        {
          "name": "Pass arguments and results between calls",
          "blurb": "Passes arguments and options into a called file and returns its result on success.",
          "hasTests": true,
          "testsDone": false,
          "builtDone": false,
          "status": "waiting"
        },
        {
          "name": "Match call style to file type",
          "blurb": "Chooses how a called file runs based on its mode, with its own model and tools.",
          "hasTests": true,
          "testsDone": false,
          "builtDone": false,
          "status": "waiting"
        },
        {
          "name": "Cancel nested calls cleanly",
          "blurb": "Adds a cancellation check at call sites and keeps a finished call's effects.",
          "hasTests": true,
          "testsDone": false,
          "builtDone": false,
          "status": "waiting"
        }
      ]
    },
    {
      "key": "V16",
      "label": "Safety limits",
      "total": 1,
      "done": 0,
      "items": [
        {
          "name": "Decide which safety limit wins",
          "blurb": "When several safety limits could fire, picks one to show and notes the rest.",
          "hasTests": true,
          "testsDone": false,
          "builtDone": false,
          "status": "waiting"
        }
      ]
    },
    {
      "key": "V17",
      "label": "Stopping work cleanly",
      "total": 3,
      "done": 0,
      "items": [
        {
          "name": "Stop work when cancelled",
          "blurb": "Routes cancel signals through one controller so running work stops promptly.",
          "hasTests": true,
          "testsDone": false,
          "builtDone": false,
          "status": "waiting"
        },
        {
          "name": "Handle errors while cancelling",
          "blurb": "Catches faults raised during cancellation without losing the cancellation itself.",
          "hasTests": true,
          "testsDone": false,
          "builtDone": false,
          "status": "waiting"
        },
        {
          "name": "Check for cancellation at key points",
          "blurb": "Checks the cancel signal before loops, questions, tool calls, and nested calls.",
          "hasTests": true,
          "testsDone": false,
          "builtDone": false,
          "status": "waiting"
        }
      ]
    },
    {
      "key": "V18",
      "label": "Keeping up with host updates",
      "total": 4,
      "done": 0,
      "items": [
        {
          "name": "List required host capabilities",
          "blurb": "Records the host features and surfaces loom depends on, for later verification.",
          "hasTests": true,
          "testsDone": false,
          "builtDone": false,
          "status": "waiting"
        },
        {
          "name": "Audit use of host features",
          "blurb": "Checks every host feature the code touches is on the approved inventory list.",
          "hasTests": true,
          "testsDone": false,
          "builtDone": false,
          "status": "waiting"
        },
        {
          "name": "Static checks for host upgrades",
          "blurb": "Verifies version pins and host assumptions still hold when upgrading the host.",
          "hasTests": true,
          "testsDone": false,
          "builtDone": false,
          "status": "waiting"
        },
        {
          "name": "Run real checks before host upgrade",
          "blurb": "Runs a full example against an upgraded host and reverts the upgrade if it fails.",
          "hasTests": true,
          "testsDone": false,
          "builtDone": false,
          "status": "waiting"
        }
      ]
    }
  ],
  "inProgress": [],
  "blocked": [
    {
      "name": "Mark a session needing reload",
      "blurb": "Marks a swapped-in session as degraded and blocks it until reloaded."
    }
  ],
  "decisions": [
    {
      "date": "2026-06-30",
      "task": "Extension factory shell and end-to-end harness",
      "summary": "Made the extension's startup code refuse to crash by simply skipping any failed setup step, leaving the smarter 'which failures are fatal' rules and error reporting for a later piece of work.",
      "detail": "The integration spec says some startup registration failures (the command-line flag, the event subscriptions) should be fatal and abort the rest of startup, while others (the message renderer) should be skipped and startup continues. This leaf's binding requirement is only that startup never throws, runs each registration under its own try/catch, and returns synchronously. So the factory swallows-and-continues on every failed call rather than implementing the per-call fatal-vs-continue distinction or the bootstrap-failed diagnostics; those, plus the capability-probe refusal logic, are explicitly deferred to leaf V9a per the leaf text. The narrower behaviour keeps the never-throw boundary faithful while not inventing V9a's contract here."
    },
    {
      "date": "2026-06-30",
      "task": "Cross-cutting lint and architectural gates",
      "summary": "Built the code-quality guardrails as small custom checks because the off-the-shelf checker couldn't read the same-line 'this is allowed here' notes the rules rely on.",
      "detail": "The plan describes the sequential-by-default and blocking-call gates using ESLint's stock 'no-restricted-syntax' rule. That stock rule cannot inspect a flagged line's own trailing allow-comment, but the leaf's binding tests require exactly that (a same-line // allow:, // allow-sync:, or // allow-broad-catch: comment makes the construct pass). Implemented three custom comment-keyed rules in eslint-plugin-loom-local instead; Adds. prose is descriptive/illustrative while the comment-keyed pass/fail behaviour is the binding obligation, so the custom rules are the faithful implementation."
    }
  ],
  "activity": [
    "2026-06-30 V7a-T — Diagnostics-primitive tests: the src/diagnostics/diagnostic.ts seam (Diagnostic shape: severity/code/file?/range?/message/hint?/related?/masked?/details?, plus stubbed renderDiagnosticLine / renderDiagnosticBatch / assembleDiagnostics) and tests/diagnostics-primitive.test.ts. Tests pin DIAG-1 (every author-visible diagnostic carries a registry code; located `<file>:<line>:<col>: <code>: <message>`, file-only, and location-less content-line forms; hint continuation + code-less related-site lines, messages sourced from the registry Message column) and multi-error assembly (no fast-fail, no per-error loss; single Diagnostic[] ordered by (file, line, col) across an entry .loom + 2 transitively-imported .warp modules supplied out of order). Typecheck + lint clean; 7 tests red on their primary assertions (empty render / empty array) because the primitive is absent — fail-red-for-the-intended-reason; other 111 tests stay green.",
    "2026-06-30 M — Minimal end-to-end .loom slash command (SLSH-2 MVP happy path): buildMinimalLoom (src/mvp/minimal-loom.ts) parses a mode:-only frontmatter block and the single untyped @`<literal>` body query of an in-memory .loom source and returns a LoomFixture whose run drives one prompt-mode turn — pi.sendUserMessage(rendered literal) then ctx.waitForIdle() — leaving exactly one appended user+assistant turn and no diagnostic; harness-supplied single-source discovery only (no ambient src/** filesystem read, no FileSystem seam). The two M-T SLSH-2 tests go green; full suite 111 green, typecheck + lint clean.",
    "2026-06-30 M-T — Minimal end-to-end .loom slash-command tests (SLSH-2 MVP happy path): the buildMinimalLoom seam (src/mvp/minimal-loom.ts, an inert stub returning a registering-but-non-driving LoomFixture) plus two failing harness tests pinning the narrowest vertical — a single in-memory .loom source discovered + registered as a slash command, dispatched, its mode: prompt frontmatter parsed, its single untyped @-query issued as one prompt-mode turn whose streamed assistant response appends as one appended turn (exactly one appended turn, no diagnostic). Harness session double extended with a pi.sendMessage diagnostics recorder (systemNotes) so the no-diagnostic assertion is observable. Tests compile (typecheck clean), lint clean, and red on their primary assertions (transcript empty) because the prompt-mode pipeline is absent — fail-red-for-the-intended-reason; remaining 109 tests stay green.",
    "2026-06-30 H5f — Per-facet citing-test closing-gate arm: extends tools/closing-gate/ (deriveFacetPartition + parseFacetRows + citesTokenInline wired into runClosingGate, plus perFacetCitingTests in loadCorpus, gated by an h5f-enabled.md marker file) to reconcile each multi-leaf coverage-matrix.md row across both the Numbered REQ-IDs and Code-keyed obligation areas tables against its facet leaves' facet-naming citing tests. For a closing-leaf cell listing two or more leaves it derives the facet partition from the cell alone (dropping a leaf whose immediately-following parenthetical contains the literal co-witness token, keeping every other listed leaf as a facet) and emits per-facet-citing-test-missing for any remaining facet with no single test source citing both the row's subject (the numbered REQ-ID, or the cka-<n> token for a code-keyed row) and that facet's closing-leaf-ID inline. Best-effort per-test-source inline existence scan — per-facet semantic fidelity stays the release-time residue item-7 obligation. Evaluated against seeded per-facet-no-violation (every facet covered, including a row whose co-witness-annotated leaf is correctly excluded from the partition) and per-facet-violation (one facet of a code-keyed multi-leaf row uncovered) fixtures under test-fixtures/closing-gate/ wired into npm test; live-corpus binding flips at H6a.",
    "2026-06-30 H5e — Un-anchored normative-MUST text-scan closing-gate arm: extends tools/closing-gate/ (parsePrefixTablePages + parseCkaAreaRows + parsePlanLeaves + pageHasUnanchoredMust + classifyClosingCell wired into runClosingGate, plus planLeavesText in loadCorpus) with the three un-anchored-obligation sub-recognisers over the non-narrative spec_topics/**-shaped pages — un-enumerated-MUST (un-anchored-must-unenumerated), <new>-placeholder-MUST (un-anchored-must-new-placeholder; a non-resolving token like V99z reddens as un-anchored-must-unresolved-leaf), and un-rowed-page (un-rowed-page-residue, excluding GOV-24 hub stubs whose filename stem matches a trailing-slash subtree row). A page is in scope iff its prefix-table cell is not the byte-exact (no IDs — narrative) literal; an un-anchored MUST (a MUST/MUST-NOT paragraph carrying no PREFIX-N REQ-ID and no loom/... registry code) must be enumerated in the Code-keyed obligation areas table with a closing-leaf token resolving to a real plan leaf. The arm runs only when the corpus supplies planLeavesText, so the H5a/H5c/H5d fixtures stay dormant. Evaluated against seeded un-anchored-no-violation / un-enumerated-must / new-placeholder-must / un-rowed-page fixtures under test-fixtures/closing-gate/ (green no-violation, red per owned violation) wired into npm test; live-corpus binding flips at H6a.",
    "2026-06-30 H5d — Transitive-completeness closing-gate arm: extends tools/closing-gate/ (parseClosingLeafCells + parseH5bDeps + expandLeafTokens wired into runClosingGate, plus h5bDepsText in loadCorpus) to reconcile every coverage-matrix.md closing-leaf cell in the Numbered REQ-IDs and Code-keyed obligation areas tables against H5b's expanded Deps. membership — tokenising each cell by its backtick spans, expanding contiguous within-group <group><letter> ranges on both sides, excluding the literal <new> placeholder and *(numbered above)* retirement cells — and emits transitive-completeness-unreachable for a per-cell at-least-one failure (a multi-leaf primary + co-witness cell stays green when one listed leaf is present, so an intentionally-excluded co-witness does not redden the arm). The arm runs only when the corpus supplies h5bDepsText, so the H5a/H5c fixtures stay dormant. Evaluated against seeded transitive-no-violation / transitive-unreachable fixtures under test-fixtures/closing-gate/ (green no-violation, red unreachable) wired into npm test; live-corpus binding flips at H6a via H5b.",
    "2026-06-30 H5c — no-broad-catch allow-list closing-gate reconciliation arm: extends tools/closing-gate/ (parseCkaTokens + extractBroadCatchEntries + a resolveBroadCatchToken predicate wired into runClosingGate, plus srcSources in loadCorpus) to scan the // allow-broad-catch: exemption comments across src/** as the lint allow-list entries and emit a broad-catch-allow-list-unresolved finding when an entry's cited token resolves to none of the four admitted arms — a coverage-matrix REQ-ID, an exactly-one cka-<n> Token cell, a concrete loom/... registry code (the resolver matches no glob/wildcard family, e.g. loom/host/session-shutdown-*), or the structural pi-sdk-boundary token. Evaluated against seeded broad-catch-no-violation / broad-catch-unresolved fixtures under test-fixtures/closing-gate/ (green no-violation, red unresolved) wired into npm test; live-corpus binding flips at H6a.",
    "2026-06-30 H5a — REQ-ID / diagnostic-code closing-gate automation: tools/closing-gate/ (runClosingGate + loadCorpus + extractors) reconciles the spec REQ-ID set and the diagnostics registry against coverage-matrix.md and the asserting/citing test corpus, returning one structured finding per gap (kinds: unmapped-executable-req-id, mapped-req-id-no-citing-test, registry-code-no-asserting-test, asserted-code-not-in-registry, retired-live-id-clash, per-prefix-numbering-hole) without throwing or gating the live corpus; loom/typecheck/* excluded from registry reconciliation; citing-test scan is best-effort inline PREFIX-N existence. Evaluated against seeded fixtures under test-fixtures/closing-gate/ (green no-violation, red per owned violation) wired into npm test.",
    "2026-06-30 H4c — Modeled-behaviour response-programming surface: extends H4b's scripting contract (tests/harness/response-program.ts, reached via double.responses / driveResponses()) with the two modelling categories V4c/V4f/V9i/V9o consume — (f) scriptInvokeChild driving a nested invoke(...) child to completion, surfacing its produced final value as a completed-invoke-child outcome (ERR-13 no-rollback), and (g) scriptSubagentCallee dispatching a private subagent AgentSession per the V9i contract, resolving the subagent-loom outcome from the terminal agent_end event and ignoring willRetry:true events (PIC-43) rather than emitting a plain scripted turn; determinism gate + per-category functional-effect self-checks wired into npm test.",
    "2026-06-30 H4b — Response-programming surface: a single deterministic input-side scripting API (tests/harness/response-program.ts, reached through H4a's harness via double.responses / driveResponses()) extending H4a's minimal response-emission into categories (a) scripted assistant turns + per-turn streamed fragments, (b) tool_use results incl. isError:true and mixed-success parallel batches (V14b), (c) binder/provider response & failure honouring the V11f per-invocation retry budget (≤3 calls: 1 + 1 transport + 1 malformed, per determinism-cancellation-failure.md), (d) tool_loop.max_rounds round-exhaustion (ERR-19/FRNT-1, V13c), and (e) abort injection at pre-call/in-flight/during-retry (V11f/V17a); determinism gate + per-category functional-effect self-checks wired into npm test.",
    "2026-06-30 H4a — Extension factory shell + end-to-end harness: never-throw synchronous-arm src/extension/factory.ts (per-call try/catch Pi-SDK-boundary registrations of the --loom flag, the loom-system-note renderer, and the resources_discover/session_start/session_shutdown subscriptions; registerCommand fires from session_start), the thin extensions/index.ts entry shim re-exporting the factory, an in-memory fixture-supply seam (LoomExtensionDeps.fixtures) M/M-T bind against, and a reusable in-process session double + harness with a minimal response-emission capability; session-double fidelity-contract self-check (streaming-before-idle, single-turn append, pi.on cancel-forward subscription, CNCL-4 reason propagation) wired into npm test. tsconfig now includes extensions/.",
    "2026-06-30 H3a — Dependency-injection seam skeleton: the seven host-seam interfaces (Checkpoint/SchemaValidator/Clock/FileSystem/FileWatcher/TokenEstimator/IdSource, PIC-10/11/12/13/14/16/20) under src/seams/, a constructor-injection RuntimeRoot + createRuntimeRoot factory threading them, and an identifier-keyed ambient-primitive scan (process.env/process.cwd/crypto.randomUUID + the PIC-12 timing set, // allow-ambient: comment-keyed) wired into npm test over src/**; two-runtime-root isolation and the direct-reference ambient ban asserted."
  ]
};
